"""``speceval init`` — create a speceval.yaml template."""

from __future__ import annotations

from pathlib import Path

import typer
from rich.console import Console
from rich.prompt import Prompt

console = Console()

_TEMPLATE = """# speceval.yaml — Evaluation specification
# Generated by `speceval init`

spec_version: "1.0"

# Model to evaluate
model:
  provider: openai          # openai | anthropic | huggingface | custom
  name: gpt-4o-mini
  # api_key: <set via env SPEKEVAL_API_KEY_...>

# Dataset to evaluate on
dataset:
  source: huggingface       # huggingface | json | csv | inline
  path: openai/gsm8k
  subset: main
  split: test
  input_template: "{question}"
  reference_field: answer

# Metrics to compute
metrics:
  - exact_match

# Number of trials (set >1 for stochastic models)
trials: 1

# Output / caching
output_dir: ./speceval_results
cache: true
"""


def run(
    path: str = typer.Option(
        "speceval.yaml",
        "--path",
        "-p",
        help="Path to write the YAML template.",
    ),
    interactive: bool = typer.Option(
        False,
        "--interactive",
        "-i",
        help="Prompt for configuration interactively.",
    ),
) -> None:
    """Create a speceval.yaml evaluation specification template."""
    dest = Path(path)

    if dest.exists():
        overwrite = typer.confirm(f"{dest} already exists. Overwrite?", default=False)
        if not overwrite:
            typer.echo("Aborting.")
            raise typer.Exit()

    if interactive:
        _interactive_init(dest)
    else:
        dest.write_text(_TEMPLATE)
        console.print(f"[green]✔[/green] Created {dest}")
        console.print("Edit the file with your model, dataset, and metrics, then run:")
        console.print(f"  [bold]speceval run --spec {dest}[/bold]")


def _interactive_init(dest: Path) -> None:
    """Interactive prompt mode."""
    provider = Prompt.ask("Model provider", default="openai")
    model = Prompt.ask("Model name", default="gpt-4o-mini")
    dataset_source = Prompt.ask("Dataset source", default="huggingface")
    dataset_path = Prompt.ask("Dataset path", default="openai/gsm8k")
    dataset_split = Prompt.ask("Dataset split", default="test")
    input_template = Prompt.ask("Input template", default="{question}")
    reference_field = Prompt.ask("Reference field", default="answer")
    metrics_str = Prompt.ask("Metrics (comma-separated)", default="exact_match")
    metrics = [m.strip() for m in metrics_str.split(",")]

    lines = [
        'spec_version: "1.0"',
        "",
        "model:",
        f'  provider: {provider}',
        f'  name: {model}',
        "",
        "dataset:",
        f'  source: {dataset_source}',
        f'  path: {dataset_path}',
        f'  split: {dataset_split}',
        f'  input_template: "{input_template}"',
        f'  reference_field: {reference_field}',
        "",
        "metrics:",
    ]
    for m in metrics:
        lines.append(f"  - {m}")
    lines.extend(["", "trials: 1", "output_dir: ./speceval_results", "cache: true"])

    dest.write_text("\n".join(lines) + "\n")
    console.print(f"[green]✔[/green] Created interactive config at {dest}")
